# Generated by Django 3.0.7 on 2020-07-09 07:34

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='city',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
