# Generated by Django 3.0.7 on 2020-07-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200709_1304'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='city',
            managers=[
            ],
        ),
    ]
